---

- hosts: localhost
  connection: local
  vars:
    required_dir:
      - "/opt"
      - "/opt/discord-bot"
      - "/opt/discord-bot/wakowako"

  tasks:
    - name: ensure necessary directory is created
      file:
        state: directory
        mode: 0755
        path: "{{ item }}"
      with_items: "{{ required_dir }}"

#    - name: ensure nodejs source is added
#      shell: curl -sL https://deb.nodesource.com/setup_6.x | -E bash -
#      args:
#        chdir: /tmp
#      become: yes

    - name: ensure nodejs is installed
      apt:
        name: nodejs
        state: latest
        install_recommends: no
      become: yes

    - name: ensure pm2 is installed
      npm:
        name: pm2
        global: yes
        state: latest
      become: yes

    - name: ensure pm2 log is symlinked to /var/log dir
      file:
        state: link
        src: /root/.pm2/logs
        path: /var/log/pm2
        mode: 0755
      become: yes
